### ISSUE TITLE
博客系统问题集中讨论帖

### ISSUE THREAD

**Issue by calpa** [calpa/gatsby-starter-calpa-blog#129]
如果你在使用这个脚手架的时候遇到任何问题，你可以在下面留言。

**Comment by medmin** [comment]
你的博客左侧最新文章栏目，404，应该是url不对

**Comment by calpa** [comment]
@medmin 可以提供一下哪个页面，点击哪个链接吗？

**Comment by medmin** [comment]
就是首页
“最新文章”
随便点击一下
https://calpa.me/2019/01/19/10-years-challenge-vertical-horizontal-center-alignment/

**Comment by calpa** [comment]
@medmin 应该是时区问题，你在哪个时区？

**Comment by medmin** [comment]
美国加州

Calpa Liu <notifications@github.com> 于 2019年1月19日周六 19:03写道：

**Comment by calpa** [comment]
@medmin 这确实是个问题，现在博客文章是使用年月日+文章标题，所以会有问题。。。。

**Comment by medmin** [comment]
那即便是用月，每个月也会有那么几个小时出错

用年，是每年有那么几个小时出错

哈哈

Calpa Liu <notifications@github.com> 于 2019年1月19日周六 19:41写道：

**Comment by medmin** [comment]
就不要加日期嘛，这不就结了？

**Comment by jerrychen1013** [comment]
嗨，博主。我啥么都没动，按原本设定部署Netify，却page noe found，该改哪儿呢？

**Comment by calpa** [comment]
@jerrychen1013 应该是 Netlify 没有运行构建脚本，比如说构建命令应该是 `npm run build`，然后生成的静态文件夹目录应该是 `public`

**Comment by jerrychen1013** [comment]
> @jerrychen1013 应该是 Netlify 没有运行构建脚本，比如说构建命令应该是 `npm run build`，然后生成的静态文件夹目录应该是 `public`

有惹，我在netify.toml加入code，成功。谢谢博主
`
[build]
  publish = "public"
  command = "npm run build"
`

**Comment by efah** [comment]
直接從 readme 的 Deploy with Netlify，但顯示 Deploy failed

```
6:45:35 PM: Build ready to start
6:45:37 PM: build-image version: 09c2cdcdf242cf2f57c9ee0fcad9d298fad9ad41
6:45:37 PM: build-image tag: v3.5.0
6:45:37 PM: buildbot version: 8df8a50b1177b0b57364d20e0ea150448924cebf
6:45:37 PM: Fetching cached dependencies
6:45:37 PM: Failed to fetch cache, continuing with build
6:45:37 PM: Starting to prepare the repo for build
6:45:37 PM: No cached dependencies found. Cloning fresh repo
6:45:37 PM: git clone https://github.com/calpa/gatsby-starter-calpa-blog
6:45:40 PM: Preparing Git Reference refs/heads/master
6:45:41 PM: Starting build script
6:45:42 PM: Installing dependencies
6:45:42 PM: Python version set to 2.7
6:45:42 PM: Attempting node version 'v8.5.0' from .nvmrc
6:45:43 PM: Downloading and installing node v8.5.0...
6:45:44 PM: Downloading https://nodejs.org/dist/v8.5.0/node-v8.5.0-linux-x64.tar.xz...
6:45:44 PM: Computing checksum with sha256sum
6:45:44 PM: Checksums matched!
6:45:46 PM: Now using node v8.5.0 (npm v5.3.0)
6:45:46 PM: Started restoring cached build plugins
6:45:46 PM: Finished restoring cached build plugins
6:45:47 PM: Attempting ruby version 2.7.1, read from environment
6:45:48 PM: Using ruby version 2.7.1
6:45:49 PM: Using PHP version 5.6
6:45:49 PM: Started restoring cached node modules
6:45:49 PM: Finished restoring cached node modules
6:45:49 PM: Installing NPM modules using NPM version 5.3.0
6:45:53 PM: npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
6:45:56 PM: npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
6:45:56 PM: npm WARN notice [SECURITY] sanitize-html has the following vulnerability: 1 critical. Go here for more details: https://www.npmjs.com/advisories?search=sanitize-html&version=1.27.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
6:45:57 PM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
6:45:58 PM: npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
6:45:59 PM: npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
6:46:01 PM: npm WARN notice [SECURITY] yargs-parser has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=yargs-parser&version=10.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
6:46:02 PM: npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
6:46:02 PM: npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
6:46:02 PM: npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
6:46:02 PM: npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
6:46:02 PM: npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
6:46:03 PM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
6:46:05 PM: npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
6:46:08 PM: npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
6:46:08 PM: npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
6:46:09 PM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
6:46:09 PM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
6:46:10 PM: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
6:46:12 PM: npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
6:46:14 PM: npm WARN deprecated highlight.js@8.9.1: Version no longer supported. Upgrade to @latest
6:47:13 PM: > bufferutil@4.0.2 install /opt/build/repo/node_modules/bufferutil
6:47:13 PM: > node-gyp-build
6:47:14 PM: make: Entering directory '/opt/build/repo/node_modules/bufferutil/build'
6:47:14 PM:   CC(target) Release/obj.target/bufferutil/src/bufferutil.o
6:47:14 PM: ../src/bufferutil.c: In function ‘Init’:
6:47:14 PM: ../src/bufferutil.c:156:12: error: too many arguments to function ‘napi_create_function’
6:47:14 PM:    status = napi_create_function(env, NULL, 0, Mask, NULL, &mask);
6:47:14 PM:             ^
6:47:14 PM: In file included from ../src/bufferutil.c:3:0:
6:47:14 PM: /opt/buildhome/.node-gyp/8.5.0/include/node/node_api.h:157:25: note: declared here
6:47:14 PM:  NAPI_EXTERN napi_status napi_create_function(napi_env env,
6:47:14 PM:                          ^
6:47:14 PM: ../src/bufferutil.c:159:12: error: too many arguments to function ‘napi_create_function’
6:47:14 PM:    status = napi_create_function(env, NULL, 0, Unmask, NULL, &unmask);
6:47:14 PM:             ^
6:47:14 PM: In file included from ../src/bufferutil.c:3:0:
6:47:14 PM: /opt/buildhome/.node-gyp/8.5.0/include/node/node_api.h:157:25: note: declared here
6:47:14 PM:  NAPI_EXTERN napi_status napi_create_function(napi_env env,
6:47:14 PM:                          ^
6:47:14 PM: ../src/bufferutil.c: At top level:
6:47:14 PM: ../src/bufferutil.c:171:35: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
6:47:14 PM:  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
6:47:14 PM:                                    ^
6:47:14 PM: /opt/buildhome/.node-gyp/8.5.0/include/node/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
6:47:14 PM:        regfunc,                                                        \
6:47:14 PM:        ^
6:47:14 PM: ../src/bufferutil.c:171:1: note: in expansion of macro ‘NAPI_MODULE’
6:47:14 PM:  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
6:47:14 PM:  ^
6:47:14 PM: ../src/bufferutil.c:171:35: note: (near initialization for ‘_module.nm_register_func’)
6:47:14 PM:  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
6:47:14 PM:                                    ^
6:47:14 PM: /opt/buildhome/.node-gyp/8.5.0/include/node/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
6:47:14 PM:        regfunc,                                                        \
6:47:14 PM:        ^
6:47:14 PM: ../src/bufferutil.c:171:1: note: in expansion of macro ‘NAPI_MODULE’
6:47:14 PM:  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
6:47:14 PM:  ^
6:47:14 PM: bufferutil.target.mk:101: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
6:47:14 PM: make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
6:47:14 PM: make: Leaving directory '/opt/build/repo/node_modules/bufferutil/build'
6:47:14 PM: gyp ERR! build error
6:47:14 PM: gyp ERR! stack Error: `make` failed with exit code: 2
6:47:14 PM: gyp ERR! stack     at ChildProcess.onExit (/opt/build/repo/node_modules/node-gyp/lib/build.js:262:23)
6:47:14 PM: gyp ERR! stack     at emitTwo (events.js:125:13)
6:47:14 PM: gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
6:47:14 PM: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
6:47:14 PM: gyp ERR! System Linux 4.19.112+
6:47:14 PM: gyp ERR! command "/opt/buildhome/.nvm/versions/node/v8.5.0/bin/node" "/opt/build/repo/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
6:47:14 PM: gyp ERR! cwd /opt/build/repo/node_modules/bufferutil
6:47:14 PM: gyp ERR! node -v v8.5.0
6:47:14 PM: gyp ERR! node-gyp -v v3.8.0
6:47:14 PM: gyp ERR! not ok
6:47:20 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/babel-plugin-add-module-exports/node_modules/chokidar/node_modules/fsevents):
6:47:20 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:47:20 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
6:47:20 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:47:20 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
6:47:20 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:47:20 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
6:47:20 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:47:20 PM: npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of @types/webpack@4.x but none was installed.
6:47:20 PM: npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of sockjs-client@^1.4.0 but none was installed.
6:47:20 PM: npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none was installed.
6:47:20 PM: npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none was installed.
6:47:20 PM: npm WARN babel-preset-gatsby@0.7.0 requires a peer of core-js@^3.0.0 but none was installed.
6:47:20 PM: npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint@6.x but none was installed.
6:47:20 PM: npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
6:47:20 PM: npm WARN ts-node@9.0.0 requires a peer of typescript@>=2.7 but none was installed.
6:47:20 PM: npm WARN react-flip-move@2.9.14 requires a peer of react@0.13.x || 0.14.x || 15.x.x but none was installed.
6:47:20 PM: npm WARN react-flip-move@2.9.14 requires a peer of react-dom@0.13.x || 0.14.x || 15.x.x but none was installed.
6:47:20 PM: npm WARN blog@1.0.0 No repository field.
6:47:20 PM: npm ERR! code ELIFECYCLE
6:47:20 PM: npm ERR! errno 1
6:47:20 PM: npm ERR! bufferutil@4.0.2 install: `node-gyp-build`
6:47:20 PM: npm ERR! Exit status 1
6:47:20 PM: npm ERR!
6:47:20 PM: npm ERR! Failed at the bufferutil@4.0.2 install script.
6:47:20 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
6:47:20 PM: npm ERR! A complete log of this run can be found in:
6:47:20 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-25T10_47_20_770Z-debug.log
6:47:20 PM: Error during NPM install
6:47:20 PM: Build was terminated: Build script returned non-zero exit code: 1
6:47:20 PM: Failing build: Failed to build site
6:47:20 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
6:47:21 PM: Finished processing build request in 1m43.967454311s
```
